app_name = "vcl_job_cards"
app_title = "VCL Job Card Tracking"
app_publisher = "Vimit Converters Limited"
app_description = "Comprehensive job card management system with Dies integration, auto-population, and intelligent validation for VCL manufacturing operations"
app_email = "tanuj@vimitconverters.com"
app_license = "mit"
required_apps = ["erpnext"]
fixtures = []
hide_in_installer = []
